[package]
name = "learnrust"
version = "0.1.0"
authors = ["andrewananta <kuro.ketanitem@gmail.com>"]
license = "MIT OR Apache-2.0"

[dependencies]
rand = "0.3.14"


[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3